apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
      - name: loan
        image: loan:1
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: loan
  labels:
    app: loan
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 3002
      targetPort: 3002
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: loan
